### ISSUE TITLE
when i run dream 'sharing a sunset at the summit of mount everest with my dog'  ,i got error :NameError: name 'image' is not defined

### ISSUE THREAD

**Issue by Kayce001** [lucidrains/DALLE2-pytorch#13]
when i run dream 'sharing a sunset at the summit of mount everest with my dog'  ,i got error :NameError: **name 'image' is not defined.**

**detail:** Traceback (most recent call last):
  File "/home/am/.local/bin/dream", line 8, in <module>
    sys.exit(dream())
  File "/home/am/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/am/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/am/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/am/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/am/.local/lib/python3.6/site-packages/dalle2_pytorch/cli.py", line 9, in dream
    return image

**Comment by lucidrains** [comment]
The command line tool isn't ready yet. If the work in progress label is there, it isn't done
