### ISSUE TITLE
Error installing Dalle2-Pytorch- module youtokentome

### ISSUE THREAD

**Issue by saurabhgayali** [lucidrains/DALLE2-pytorch#132]
I am having error while installation. probably due to youtokentome

```
Collecting dalle2-pytorchdone
  error: subprocess-exited-with-error
  
  python setup.py egg_info did not run successfully.
  exit code: 1
  
  [6 lines of output]
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\saurabh.gayali\AppData\Local\Temp\pip-install-ladp9dcm\youtokentome_7e78bf3ba9904ff7af5d9bbcebde25cf\setup.py", line 5, in <module>
      from Cython.Build import cythonize
  ModuleNotFoundError: No module named 'Cython'
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

  Using cached dalle2_pytorch-0.6.5-py3-none-any.whl (1.4 MB)
Collecting rotary-embedding-torch
  Using cached rotary_embedding_torch-0.1.5-py3-none-any.whl (4.1 kB)
Collecting resize-right>=0.0.2
  Using cached resize_right-0.0.2-py3-none-any.whl (8.9 kB)
Collecting pydantic
  Using cached pydantic-1.9.1-cp38-cp38-win_amd64.whl (2.1 MB)
Collecting kornia>=0.5.4
  Using cached kornia-0.6.5-py2.py3-none-any.whl (512 kB)
Collecting einops>=0.4
  Downloading einops-0.4.1-py3-none-any.whl (28 kB)
Collecting webdataset>=0.2.5
  Using cached webdataset-0.2.5-py3-none-any.whl (46 kB)
Collecting embedding-reader
  Using cached embedding_reader-1.4.2-py3-none-any.whl (17 kB)
Collecting clip-anytorch
  Using cached clip_anytorch-2.4.0-py3-none-any.whl (1.4 MB)
Collecting torchvision
  Using cached torchvision-0.12.0-cp38-cp38-win_amd64.whl (1.0 MB)
Collecting torchmetrics[image]>=0.8.0
  Downloading torchmetrics-0.9.0-py3-none-any.whl (418 kB)
     -------------------------------------- 418.2/418.2 kB 1.6 MB/s eta 0:00:00
Collecting tqdm
  Using cached tqdm-4.64.0-py2.py3-none-any.whl (78 kB)
Collecting einops-exts>=0.0.3
  Using cached einops_exts-0.0.3-py3-none-any.whl (3.8 kB)
Collecting x-clip>=0.4.4
  Downloading x_clip-0.6.1-py3-none-any.whl (1.4 MB)
     ---------------------------------------- 1.4/1.4 MB 6.7 MB/s eta 0:00:00
Collecting youtokentome
  Using cached youtokentome-1.0.6.tar.gz (86 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by lucidrains** [comment]
@saurabhgayali hey Saurabh! decided to just make youtokentome optional, as it isn't an essential package yet https://github.com/lucidrains/DALLE2-pytorch/commit/a851168633968219ef88e6fac7a760018ac756f9 hope this helps!
